// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: identifier.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_identifier_proto protoreflect.FileDescriptor

const file_identifier_proto_rawDesc = "" +
	"\n" +
	"\x10identifier.proto\x12\bresource\x1a\x0eidentity.proto\x1a\x0eresource.proto2\xb1\x01\n" +
	"\n" +
	"Identifier\x12:\n" +
	"\fAuthenticate\x12\x12.resource.Identity\x1a\x12.resource.Resource(\x010\x01\x123\n" +
	"\tAuthority\x12\x12.resource.Identity\x1a\x12.resource.Identity\x122\n" +
	"\bIdentify\x12\x12.resource.Resource\x1a\x12.resource.IdentityB*Z(github.com/accretional/proto-resource/pbb\x06proto3"

var file_identifier_proto_goTypes = []any{
	(*Identity)(nil), // 0: resource.Identity
	(*Resource)(nil), // 1: resource.Resource
}
var file_identifier_proto_depIdxs = []int32{
	0, // 0: resource.Identifier.Authenticate:input_type -> resource.Identity
	0, // 1: resource.Identifier.Authority:input_type -> resource.Identity
	1, // 2: resource.Identifier.Identify:input_type -> resource.Resource
	1, // 3: resource.Identifier.Authenticate:output_type -> resource.Resource
	0, // 4: resource.Identifier.Authority:output_type -> resource.Identity
	0, // 5: resource.Identifier.Identify:output_type -> resource.Identity
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identifier_proto_init() }
func file_identifier_proto_init() {
	if File_identifier_proto != nil {
		return
	}
	file_identity_proto_init()
	file_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identifier_proto_rawDesc), len(file_identifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identifier_proto_goTypes,
		DependencyIndexes: file_identifier_proto_depIdxs,
	}.Build()
	File_identifier_proto = out.File
	file_identifier_proto_goTypes = nil
	file_identifier_proto_depIdxs = nil
}
