// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: openmode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenMode specifies the authorized interactions within the scope of an open session
type OpenMode int32

const (
	OpenMode_OPEN_MODE_UNKNOWN OpenMode = 0
	OpenMode_READ              OpenMode = 1 // OREAD - open for reading
	OpenMode_WRITE             OpenMode = 2 // OWRITE - open for writing
	OpenMode_EXEC              OpenMode = 3 // OEXEC - open for execution
	OpenMode_WTRUNC            OpenMode = 4 // OTRUNC - truncate file on open, ie rewrite/set it
	OpenMode_RCLOSE            OpenMode = 5 // ORCLOSE - remove file on close, ie it only exists within this session
)

// Enum value maps for OpenMode.
var (
	OpenMode_name = map[int32]string{
		0: "OPEN_MODE_UNKNOWN",
		1: "READ",
		2: "WRITE",
		3: "EXEC",
		4: "WTRUNC",
		5: "RCLOSE",
	}
	OpenMode_value = map[string]int32{
		"OPEN_MODE_UNKNOWN": 0,
		"READ":              1,
		"WRITE":             2,
		"EXEC":              3,
		"WTRUNC":            4,
		"RCLOSE":            5,
	}
)

func (x OpenMode) Enum() *OpenMode {
	p := new(OpenMode)
	*p = x
	return p
}

func (x OpenMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenMode) Descriptor() protoreflect.EnumDescriptor {
	return file_openmode_proto_enumTypes[0].Descriptor()
}

func (OpenMode) Type() protoreflect.EnumType {
	return &file_openmode_proto_enumTypes[0]
}

func (x OpenMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenMode.Descriptor instead.
func (OpenMode) EnumDescriptor() ([]byte, []int) {
	return file_openmode_proto_rawDescGZIP(), []int{0}
}

var File_openmode_proto protoreflect.FileDescriptor

const file_openmode_proto_rawDesc = "" +
	"\n" +
	"\x0eopenmode.proto\x12\bresource*X\n" +
	"\bOpenMode\x12\x15\n" +
	"\x11OPEN_MODE_UNKNOWN\x10\x00\x12\b\n" +
	"\x04READ\x10\x01\x12\t\n" +
	"\x05WRITE\x10\x02\x12\b\n" +
	"\x04EXEC\x10\x03\x12\n" +
	"\n" +
	"\x06WTRUNC\x10\x04\x12\n" +
	"\n" +
	"\x06RCLOSE\x10\x05B*Z(github.com/accretional/proto-resource/pbb\x06proto3"

var (
	file_openmode_proto_rawDescOnce sync.Once
	file_openmode_proto_rawDescData []byte
)

func file_openmode_proto_rawDescGZIP() []byte {
	file_openmode_proto_rawDescOnce.Do(func() {
		file_openmode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmode_proto_rawDesc), len(file_openmode_proto_rawDesc)))
	})
	return file_openmode_proto_rawDescData
}

var file_openmode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openmode_proto_goTypes = []any{
	(OpenMode)(0), // 0: resource.OpenMode
}
var file_openmode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openmode_proto_init() }
func file_openmode_proto_init() {
	if File_openmode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmode_proto_rawDesc), len(file_openmode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmode_proto_goTypes,
		DependencyIndexes: file_openmode_proto_depIdxs,
		EnumInfos:         file_openmode_proto_enumTypes,
	}.Build()
	File_openmode_proto = out.File
	file_openmode_proto_goTypes = nil
	file_openmode_proto_depIdxs = nil
}
