// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: session.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encodes a token with name=<secret> and owners=<provenance> stemming from the user's Identity they used to Authenticate with via the Identifier
	User *Resource `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// id is persistent, name is consumed when Session is joined. User remains owner until session is joined, at which point it reverts to the system.
	Upstream *Resource `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// Since a user could open additional sessions within the scope of an active session, they may need to be aborted, cleaned up, or persisted.
	Downstream    []*Session `protobuf:"bytes,3,rep,name=downstream,proto3" json:"downstream,omitempty"`
	Omode         OpenMode   `protobuf:"varint,4,opt,name=omode,proto3,enum=resource.OpenMode" json:"omode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetUser() *Resource {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Session) GetUpstream() *Resource {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *Session) GetDownstream() []*Session {
	if x != nil {
		return x.Downstream
	}
	return nil
}

func (x *Session) GetOmode() OpenMode {
	if x != nil {
		return x.Omode
	}
	return OpenMode_OPEN_MODE_UNKNOWN
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\bresource\x1a\x0eresource.proto\x1a\x0eopenmode.proto\"\xbe\x01\n" +
	"\aSession\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.resource.ResourceR\x04user\x12.\n" +
	"\bupstream\x18\x02 \x01(\v2\x12.resource.ResourceR\bupstream\x121\n" +
	"\n" +
	"downstream\x18\x03 \x03(\v2\x11.resource.SessionR\n" +
	"downstream\x12(\n" +
	"\x05omode\x18\x04 \x01(\x0e2\x12.resource.OpenModeR\x05omodeB*Z(github.com/accretional/proto-resource/pbb\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_session_proto_goTypes = []any{
	(*Session)(nil),  // 0: resource.Session
	(*Resource)(nil), // 1: resource.Resource
	(OpenMode)(0),    // 2: resource.OpenMode
}
var file_session_proto_depIdxs = []int32{
	1, // 0: resource.Session.user:type_name -> resource.Resource
	1, // 1: resource.Session.upstream:type_name -> resource.Resource
	0, // 2: resource.Session.downstream:type_name -> resource.Session
	2, // 3: resource.Session.omode:type_name -> resource.OpenMode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_resource_proto_init()
	file_openmode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
